### ISSUE TITLE
Enable writing of credentials to config

### ISSUE THREAD

**Issue by 5nafu** [ImmobilienScout24/afp-cli#10]
As a windows user I would like to write the received credentials to the AWS-configuration (`.aws/credentials` in the User Directory) to enable my SDK-based application to use the credentials automatically.

With this command-line-switch I would not need to set the Environment variables manually.

**Comment by sdomme** [comment]
Works like a charm on Windows! Thanks!

**Comment by esc** [comment]
Closed by #17 , thanks for feedback @sdomme
