### ISSUE TITLE
export AWS_ACCOUNT_NAME, AWS_ACCOUNT_ID, and AWS_ACTIVE_ROLE as environment variables into afp subshell

### ISSUE THREAD

**Issue by matey-jack** [ImmobilienScout24/afp-cli#20]
this would be useful in custom scripts that run inside the shell.

If you like the feature I could try to knit a pull request.

**Comment by schlomo** [comment]
Interesting idea. Can you please provide an example use case for this data?

**Comment by matey-jack** [comment]
We have a naming convention for buckets and accounts such that we can derive, bucket names (for deployment or for logs) from the account name. Virtually all configuration of test and prod systems is the same, but for something like alarm/success notification messages, we want to put the stage (or account-name) into the message to know where it comes from.

We don't use CFN yet, but assume that when instantiating a CFN we have to fill in the stage parameter. And when switches stages on the shell between dev and test, it can be easy to forget to set the stage parameter after switching accounts with AFP.

**Comment by esc** [comment]
I'd use this in my zsh prompt so :+1:

On 30 October 2015 15:35:01 CET, Robert Jack Will notifications@github.com wrote:

> We have a naming convention for buckets and accounts such that we can
> derive, bucket names (for deployment or for logs) from the account
> name. Virtually all configuration of test and prod systems is the same,
> but for something like alarm/success notification messages, we want to
> put the stage (or account-name) into the message to know where it comes
> from.
> 
> We don't use CFN yet, but assume that when instantiating a CFN we have
> to fill in the stage parameter. And when switches stages on the shell
> between dev and test, it can be easy to forget to set the stage
> parameter after switching accounts with AFP.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ImmobilienScout24/afp-cli/issues/20#issuecomment-152542305

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by esc** [comment]
To make this universal, you probably ought to export them into the subshell and also when the user calls `write`, `show` and `export`.

**Comment by matey-jack** [comment]
I just knitted a patch, but can't test it, since `pyb` refuses running tests. Will try with my computer at home. 

Doing it for Shell automatically does it for `show` and `export`. Concerning `write` we'd need to decide where to put the information. Would it be useful as name of the profile, for example?

**Comment by esc** [comment]
@matey-jack @schlomo can we close this?
