### ISSUE TITLE
please add some install instructions

### ISSUE THREAD

**Issue by SebastianStiehl** [ImmobilienScout24/afp-cli#23]
It would be nice if there where some install instruction on top of the readme file. I would like to link the project from a howto-guide and don't wont to explain it there.

**Comment by esc** [comment]
See: #24

**Comment by SebastianStiehl** [comment]
thx

**Comment by esc** [comment]
#24 has been merged and I cut a new release, `1.2.1` which should be available from PyPi shortly.
