### ISSUE TITLE
Cannot check version and build time of installed afp-cli

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/afp-cli#33]
Currently the only place the version is stored is in the `build.py`. This means the cli can not report it's own version with `--version` for example.

**Comment by schlomo** [comment]
**Value**: 
- Quick and easy option for the end-user to determine how old his installed afp-cli is.
- track client versions on the AFP server
- prevent incompatible mixes between afp-cli and AFP server, e.g. by requiring a minimum afp-cli version on the server.
