### ISSUE TITLE
Recheck Coverage with Coveralls

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/afp-cli#35]
Coveralls seems to be reporting a strange coverage: 59% where use on the command-line via pybuilder gives 89%

**Comment by snordhausen** [comment]
Coveralls also considers files that are not imported by any unit test, while pybuilder excludes them. The behavior of Coveralls seems better to me, since I just found b1f3b80566c69954db00796e60dae42615b950f0 thanks to it. So, if anything, this is a pybuilder issue.
