### ISSUE TITLE
Handle hash in role name (?)

### ISSUE THREAD

**Issue by mriehl** [ImmobilienScout24/afp-cli#44]
I don't know if there is a use case for this (I don't have one) but afp-cli seems to truncate the role when it encounters a hash.

``` bash
» afpv2 show account-name role-\#name
Password for mriehl: 
Failed to get credentials from AWS: API call to AWS (https://afp.invalid/afp-api/latest//account/account-name/role-#name) failed: User 'mriehl' may not access role 'role-' in account 'account-name'
```

This is probably due to the hash becoming an anchor. It also allows for things like URL traversal (a malicious role name could make you log in to another account) so I think the user set parameters should be transmitted over json, not URL.

**Comment by schlomo** [comment]
I very much hope that the security checks in AFP go by the user groups (@tvollmer-at-is24, @snordhausen  can you tell ?).

**Comment by snordhausen** [comment]
Yes, afp-core uses the user's groups to check what he may access. So no matter what you send in the URL, there's a fixed set of account+role combinations that you may access. The request only serves to select one of them.

mriehl's point is valid, though. Via

```
afp-cli accountA ../accountB/myrole
```

I will actually log into accountB, not accountA (assuming, of course, I have access to accountB). Not sure if that is an issue, though, it's just how URLs work and there's no privilege escalation.

The `#` does not allow you to select a different account. We could URL-encode the parameters to allow role names that contain characters like %#/ and potentially any UTF-8 character.
