### ISSUE TITLE
Provide XDG compatible config

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/afp-cli#9]
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

:+1: for standards

**Comment by schlomo** [comment]
Which problem does this solve?
Am 27.09.2015 20:17 schrieb "Valentin Haenel" notifications@github.com:

**Comment by esc** [comment]
fix standards compliance...

But srsly, it doesn't solve anything, but I thought it would be nice to have..

**Comment by schlomo** [comment]
What would be your specific suggestion?

**Comment by esc** [comment]
Probably, not to do it, unless it solves a specific problem..

**Comment by schlomo** [comment]
Great argument to close the issue :-)

**Comment by esc** [comment]
BTW: this would be really easy to implement and test -- if we had proper command line tests and a `--debug` switch.

**Comment by esc** [comment]
@schlomo agreed!
